# Generated by Django 3.1.1 on 2020-10-02 18:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('advito', '0002_profile_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='add',
            name='favourites',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='ad',
        ),
        migrations.AlterField(
            model_name='add',
            name='date_edit',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='add',
            name='date_pub',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.TextField(max_length=64, verbose_name='название'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=700)),
                ('date_publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('in_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advito.add')),
            ],
        ),
    ]
