# Generated by Django 3.1.1 on 2020-10-16 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advito', '0004_auto_20201008_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add',
            name='date_edit',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
