# Generated by Django 3.1.1 on 2020-12-28 02:31

import advito.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advito', '0006_auto_20201228_0341'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='image',
            field=models.ImageField(blank=True, upload_to=advito.models.ava_path),
        ),
    ]
